export const CONTENT = {
  "common": {
    "appName": "达人探测器",
    "appDescription": "智能获客系统",
    "projectTitle": "项目管理",
    "back": "返回",
    "cancel": "取消",
    "confirm": "确定",
    "submit": "提交",
    "save": "保存",
    "delete": "删除",
    "edit": "编辑",
    "add": "添加",
    "search": "搜索",
    "loadingData": "正在获取海量数据...",
    "searchPlaceholder": "描述您的推广需求，例如：我有一款祛痘精华，想找真实战痘经历的博主做种草推广...",
    "voicePlaceholder": "正在聆听您的需求...",
    "radarPlaceholder": "补充雷达筛选条件",
    "aiAnalyzing": "AI 深度解析需求中...",
    "voiceAnalyzing": "语音分析中...",
    "radarAnalyzing": "雷达匹配分析",
    "multiSelect": "(可多选)",
    "unlimited": "不限",
    "total": "总计",
    "page": "页",
    "showing": "显示第",
    "of": "条，共",
    "unit": "条",
    "selected": "已选择",
    "tagsUnit": "个标签",
    "publishedRecently": "发布于最近",
    "reason": "原因",
    "inputReason": "请输入不通过的理由...",
    "followersSuffix": "粉丝"
  },
  "radarPage": {
    "title": "达人探测器",
    "expandSearch": "展开搜索",
    "aiAnalysis": "智能分析",
    "initialSearch": "我们有一款祛痘精华液，想找有真实战痘经历、粉丝粘性高的护肤博主做种草推广，预算3000以内，优先找正在记录祛痘过程的达人。",
    "inputPlaceholder": "例如：祛痘产品推广，找有烂脸自救经历的博主，预算5000以内...",
    "buttonText": "开始搜寻",
    "aiRecommendation": {
      "title": "AI 推荐策略",
      "intro": "根据您关于",
      "requirements": "的推广需求，AI 为您分析如下：",
      "locationRec": "建议优先选择 广东、浙江、江苏 地区的达人，这些地区护肤类内容创作者密度最高，粉丝购买力强。",
      "typeRec": "推荐筛选「战痘日记」「烂脸自救」类标签的达人，这类博主有真实祛痘经历，粉丝信任度高，种草转化率比纯测评高出 37%。",
      "footer": "建议优先选择粉丝量 1000-5万 的中小博主，性价比高且互动率更好。您可以调整筛选条件进一步精确匹配。"
    },
    "filters": {
      "title": "筛选条件",
      "tags": "标签",
      "moreTags": "更多标签",
      "price": "价格",
      "followers": "粉丝数",
      "region": "地区",
      "moreRegions": "更多地址",
      "contentType": "内容类型",
      "startSearch": "开始搜寻",
      "priceOptions": ["不限", "500以下", "500-1500", "1500-3000", "3000-8000", "8000-2.5W", "2.5W以上"],
      "followerOptions": ["不限", "1000以下", "1000-5000", "5000-1W", "1W-5W", "5W-10W", "10W以上"],
      "filterButton": "执行筛选"
    }
  },
  "resultsPage": {
    "title": "找更多达人",
    "matchConditions": "匹配条件",
    "startRadar": "找更多达人",
    "precisionSearch": {
      "title": "精准筛选",
      "placeholder": "请输入更具体的筛选要求，例如：有真实前后对比照、提到过具体祛痘产品、评论区有粉丝追问的笔记...",
      "button": "精准筛选",
      "advancedButton": "高级筛选",
      "scanning": "正在深度扫描达人笔记...",
      "matchImage": "通过笔记图片匹配",
      "matchContent": "通过笔记内容匹配",
      "matchReason": "匹配原因"
    },
    "sortBy": "排序方式",
    "totalFound": "共找到",
    "unit": "位达人",
    "table": {
      "info": "达人信息",
      "regionType": "地区/类型",
      "followers": "粉丝数",
      "recentPosts": "匹配笔记",
      "postCount": "笔记数",
      "price": "参考报价",
      "action": "操作"
    },
    "sortOptions": [
      { "id": "followers", "label": "按粉丝数" },
      { "id": "price", "label": "按价格" },
      { "id": "views", "label": "按阅读量" },
      { "id": "posts", "label": "按笔记数" }
    ]
  },
  "project": {
    "projectTitle": "项目管理",
    "selectProject": "选择项目",
    "selectProjectHint": "请从左侧选择一个项目查看达人",
    "createProject": "新建项目",
    "newProject": "新建项目",
    "projectName": "项目名称",
    "projectNamePlaceholder": "请输入项目名称...",
    "projectDesc": "项目描述",
    "projectDescPlaceholder": "请输入项目描述...",
    "inputName": "请输入项目名称",
    "inputDesc": "请输入项目描述",
    "addToProject": "加入项目",
    "approve": "通过",
    "reject": "不通过",
    "rejectReason": "不通过理由",
    "rejectReasonPlaceholder": "请填写不通过的原因，以便后续优化匹配...",
    "batchApprove": "批量通过",
    "batchReject": "批量不通过",
    "batchContact": "智能建联",
    "batchDM": "批量评论",
    "remove": "移除",
    "approved": "已通过",
    "cancelApprove": "取消通过",
    "rejected": "已拒绝",
    "defaultProjectName": "默认项目",
    "projectList": "项目列表",
    "influencerList": "达人列表",
    "noInfluencers": "该项目暂无达人",
    "emptyProject": "该项目暂无达人",
    "backToSelect": "返回选择已有项目"
  },
  "displayPage": {
    "title": "找更多达人",
    "subtitle": "根据AI智能分析，通过笔记、照片内容进行深度匹配",
    "matchAnalysis": "雷达匹配分析",
    "matchReason": "雷达匹配原因",
    "intro": "达人简介",
    "postPreview": "匹配笔记预览",
    "fitScore": "匹配",
    "statusTexts": [
      "正在匹配有真实战痘经历的博主...",
      "分析笔记内容，筛选提及祛痘产品的达人...",
      "扫描前后对比照，识别真实效果展示...",
      "计算粉丝互动率，评估种草转化潜力...",
      "筛选评论区活跃度高的优质达人...",
      "综合评分排序，输出最佳推广人选..."
    ]
  },
  "influencerDetail": {
    "fitScore": "匹配度",
    "followers": "粉丝",
    "recentPosts": "最近笔记内容",
    "collect": "收藏达人"
  },
  "postDetail": {
    "content": "笔记正文",
    "aiAnalysis": "AI 匹配分析",
    "views": "阅读量",
    "comments": "评论数",
    "likes": "热度值"
  },
  "contact": {
    "title": "智能建联",
    "subtitle": "跨项目达人建联管理",
    "info": "达人信息",
    "project": "所属项目",
    "status": "建联状态",
    "action": "对话",
    "finishContact": "完成建联",
    "chatTitle": "建联对话记录",
    "statusMap": {
      "waiting_follow": "等待关注",
      "contacting": "建联中",
      "no_reply": "评论未回复",
      "accepted": "已同意",
      "declined": "已拒绝",
      "need_human": "需人工介入",
      "completed": "完成建联"
    },
    "noRecords": "暂无建联记录",
    "initHint": "正在初始化建联任务...",
    "totalCount": "共",
    "unit": "位达人",
    "scriptManagement": "话术管理",
    "scriptTitle": "话术管理",
    "scriptSubtitle": "配置不同场景下的自动回复话术，AI将根据对话情况自动选择合适的话术",
    "scriptConfirm": "确认话术",
    "scriptReset": "恢复默认",
    "scriptCategories": {
      "greeting": "打招呼",
      "project_intro": "发送项目介绍",
      "no_reply_followup": "长时间未回复",
      "declined": "对方拒绝",
      "accepted": "对方同意",
      "price_rejected": "对方拒绝报价"
    },
    "scriptCategoryDescriptions": {
      "greeting": "首次联系达人时的开场白，要简洁亲切，引起对方兴趣",
      "project_intro": "达人感兴趣后，发送项目/产品的详细介绍",
      "no_reply_followup": "达人超过24小时未回复时的跟进话术",
      "declined": "达人表示暂时无法合作时的礼貌回复",
      "accepted": "达人同意合作后的确认和后续安排",
      "price_rejected": "达人对报价不满意时的协商话术"
    },
    "scriptDefaults": {
      "greeting": "宝子你好~看了你分享的内容觉得特别真实有感染力！我们这边有一些品牌合作机会想跟你聊聊，方便吗？😊",
      "project_intro": "我们是「{projectName}」项目方，目前有一款祛痘精华正在招募达人合作推广。\n\n📦 产品：氨基酸祛痘精华 30ml（国家药监局备案）\n📝 合作形式：图文笔记1篇，真实使用后分享体验\n💰 合作费用：根据粉丝量和内容质量面议\n📅 档期：本月内发布\n\n产品可以先免费寄给你试用，觉得好用再出内容～",
      "no_reply_followup": "宝子~之前给你发的合作消息看到了吗？如果你感兴趣的话可以回复我哦，产品可以先免费寄给你试用～不感兴趣也没关系，打扰啦🙏",
      "declined": "好的完全理解！感谢你的回复～后续如果有空档期欢迎随时联系我们，期待下次合作机会！🤝",
      "accepted": "太好了！非常期待合作！🎉\n接下来我会把合作详情和产品信息整理发给你，确认后尽快安排寄样。\n有任何问题随时找我哦～",
      "price_rejected": "了解你的报价～我们这边预算可能有限，但可以额外提供：\n✅ 产品正装 + 小样礼盒\n✅ 长期合作优先权\n✅ 数据好的话有额外奖励\n\n价格方面我再跟品牌方沟通看看有没有空间，稍后给你反馈好吗？"
    }
  }
};
